#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("TrainingApp.Resource", IsApplication=true)]

namespace TrainingApp
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050000
			public const int buttonChooseBack = 2131034112;
			
			// aapt resource value: 0x7f050006
			public const int buttonChooseSelectedProduct = 2131034118;
			
			// aapt resource value: 0x7f050007
			public const int buttonExit = 2131034119;
			
			// aapt resource value: 0x7f050011
			public const int buttonNewProductAdd = 2131034129;
			
			// aapt resource value: 0x7f05000b
			public const int buttonNewProductBack = 2131034123;
			
			// aapt resource value: 0x7f050009
			public const int buttonNewProfile = 2131034121;
			
			// aapt resource value: 0x7f050030
			public const int buttonOpenRation = 2131034160;
			
			// aapt resource value: 0x7f050032
			public const int buttonOpenTimer = 2131034162;
			
			// aapt resource value: 0x7f050031
			public const int buttonOpenTrainingDiary = 2131034161;
			
			// aapt resource value: 0x7f05001d
			public const int buttonPofileAdd = 2131034141;
			
			// aapt resource value: 0x7f050012
			public const int buttonPofileBack = 2131034130;
			
			// aapt resource value: 0x7f05001f
			public const int buttonProfileDelete = 2131034143;
			
			// aapt resource value: 0x7f05001e
			public const int buttonProfileEdit = 2131034142;
			
			// aapt resource value: 0x7f05002c
			public const int buttonRationAddProduct = 2131034156;
			
			// aapt resource value: 0x7f050020
			public const int buttonRationBack = 2131034144;
			
			// aapt resource value: 0x7f05002d
			public const int buttonRationNewProduct = 2131034157;
			
			// aapt resource value: 0x7f05002f
			public const int buttonSelectorBack = 2131034159;
			
			// aapt resource value: 0x7f050041
			public const int buttonSetTimeOptions = 2131034177;
			
			// aapt resource value: 0x7f05000a
			public const int buttonStartWork = 2131034122;
			
			// aapt resource value: 0x7f050033
			public const int buttonTimeOptionsBack = 2131034163;
			
			// aapt resource value: 0x7f050042
			public const int buttonTimerBack = 2131034178;
			
			// aapt resource value: 0x7f050043
			public const int buttonTimerOptions = 2131034179;
			
			// aapt resource value: 0x7f050048
			public const int buttonTimerReset = 2131034184;
			
			// aapt resource value: 0x7f050047
			public const int buttonTimerStartStop = 2131034183;
			
			// aapt resource value: 0x7f050034
			public const int editTextApproachHour = 2131034164;
			
			// aapt resource value: 0x7f050035
			public const int editTextApproachMin = 2131034165;
			
			// aapt resource value: 0x7f050036
			public const int editTextApproachSec = 2131034166;
			
			// aapt resource value: 0x7f05003d
			public const int editTextBigRelaxHour = 2131034173;
			
			// aapt resource value: 0x7f05003e
			public const int editTextBigRelaxMin = 2131034174;
			
			// aapt resource value: 0x7f05003f
			public const int editTextBigRelaxSec = 2131034175;
			
			// aapt resource value: 0x7f050005
			public const int editTextChooseProductWeight = 2131034117;
			
			// aapt resource value: 0x7f05003a
			public const int editTextCountRound = 2131034170;
			
			// aapt resource value: 0x7f050010
			public const int editTextNewProductCalls = 2131034128;
			
			// aapt resource value: 0x7f05000f
			public const int editTextNewProductCarbohydrates = 2131034127;
			
			// aapt resource value: 0x7f05000e
			public const int editTextNewProductFats = 2131034126;
			
			// aapt resource value: 0x7f05000d
			public const int editTextNewProductProteins = 2131034125;
			
			// aapt resource value: 0x7f05000c
			public const int editTextNewProductTitle = 2131034124;
			
			// aapt resource value: 0x7f050016
			public const int editTextPofileAge = 2131034134;
			
			// aapt resource value: 0x7f05001c
			public const int editTextPofileCountTraining = 2131034140;
			
			// aapt resource value: 0x7f050014
			public const int editTextPofileHeight = 2131034132;
			
			// aapt resource value: 0x7f050013
			public const int editTextPofileTitle = 2131034131;
			
			// aapt resource value: 0x7f050015
			public const int editTextPofileWeight = 2131034133;
			
			// aapt resource value: 0x7f050037
			public const int editTextSmalRelaxHour = 2131034167;
			
			// aapt resource value: 0x7f050038
			public const int editTextSmalRelaxMin = 2131034168;
			
			// aapt resource value: 0x7f050039
			public const int editTextSmalRelaxSec = 2131034169;
			
			// aapt resource value: 0x7f050003
			public const int linearLayout1 = 2131034115;
			
			// aapt resource value: 0x7f050023
			public const int linearLayout2 = 2131034147;
			
			// aapt resource value: 0x7f050022
			public const int linearLayout3 = 2131034146;
			
			// aapt resource value: 0x7f05003b
			public const int linearLayout4 = 2131034171;
			
			// aapt resource value: 0x7f050040
			public const int linearLayout5 = 2131034176;
			
			// aapt resource value: 0x7f05002e
			public const int listViewRationProductsInRation = 2131034158;
			
			// aapt resource value: 0x7f05001b
			public const int radioButtonPofileGain = 2131034139;
			
			// aapt resource value: 0x7f05001a
			public const int radioButtonPofileLoss = 2131034138;
			
			// aapt resource value: 0x7f050018
			public const int radioButtonPofileMan = 2131034136;
			
			// aapt resource value: 0x7f050019
			public const int radioButtonPofileWoman = 2131034137;
			
			// aapt resource value: 0x7f050017
			public const int radioGroup1 = 2131034135;
			
			// aapt resource value: 0x7f050002
			public const int spinnerChooseSelectProduct = 2131034114;
			
			// aapt resource value: 0x7f050008
			public const int spinnerProfiles = 2131034120;
			
			// aapt resource value: 0x7f050001
			public const int textView1 = 2131034113;
			
			// aapt resource value: 0x7f050004
			public const int textView2 = 2131034116;
			
			// aapt resource value: 0x7f050021
			public const int textView3 = 2131034145;
			
			// aapt resource value: 0x7f05003c
			public const int textView4 = 2131034172;
			
			// aapt resource value: 0x7f05002b
			public const int textViewRationCallsIs = 2131034155;
			
			// aapt resource value: 0x7f050027
			public const int textViewRationCallsNeed = 2131034151;
			
			// aapt resource value: 0x7f05002a
			public const int textViewRationCarbohydratesIs = 2131034154;
			
			// aapt resource value: 0x7f050026
			public const int textViewRationCarbohydratesNeed = 2131034150;
			
			// aapt resource value: 0x7f050029
			public const int textViewRationFatsIs = 2131034153;
			
			// aapt resource value: 0x7f050025
			public const int textViewRationFatsNeed = 2131034149;
			
			// aapt resource value: 0x7f050028
			public const int textViewRationProteinsIs = 2131034152;
			
			// aapt resource value: 0x7f050024
			public const int textViewRationProteinsNeed = 2131034148;
			
			// aapt resource value: 0x7f050044
			public const int textViewRound = 2131034180;
			
			// aapt resource value: 0x7f050046
			public const int textViewTime = 2131034182;
			
			// aapt resource value: 0x7f050045
			public const int textViewWhatTime = 2131034181;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int ChooseProductLayout = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int MainLayout = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int NewProductLayout = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int NewProfileLayout = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int RationLayout = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int SelectorLayout = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int TimerOptionsLayout = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int TimerWorkLayout = 2130903047;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
